(   echo "# Automatically generated by ${PACKAGE_NAME}-${PACKAGE_VERSION}"
    echo "# $(date -u)"
    echo "# Do not edit."
    cd "/$PACKAGE_NAME"/usr/share/ca-certificates
    find . -name '*.crt' | sort | cut -b3-
) > "/$PACKAGE_NAME"/etc/ca-certificates.conf 

# generate the bundle in similar way as update-ca-certificates would do
for i in $(ls *.crt | sort); do
    cat "$i"
    printf "\n"
done > "/$PACKAGE_NAME"/etc/ssl/certs/ca-certificates.crt

cd "/$PACKAGE_NAME"/etc/ssl

ln -s certs/ca-certificates.crt cert.pem