
requires:
- name: musl-toolchain
  category: system
  version: ">=0"
- name: make
  category: development
  version: ">=0"
- name: perl
  category: lang
  version: ">=0"
env:
- FORCE_UNSAFE_CONFIGURE=1

package_dir: /coreutils
prelude:
- |
   curl -L -O  http://ftp.gnu.org/gnu/${PACKAGE_NAME}/${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.xz && \
   tar -xvf ${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.xz && mv ${PACKAGE_NAME}-${PACKAGE_VERSION} ${PACKAGE_NAME} && \
   cd ${PACKAGE_NAME} && mkdir -p /${PACKAGE_NAME} && ./configure --prefix=/ && echo $CFLAGS && echo $LDFLAGS && make DESTDIR=/${PACKAGE_NAME}

steps:
- cd ${PACKAGE_NAME} && make DESTDIR=/${PACKAGE_NAME} install && make install
