
requires:
- name: musl-toolchain
  category: system
  version: ">=0"
- name: make
  category: development
  version: ">=0"
- name: perl
  category: lang
  version: ">=0"
- name: zlib
  category: libs
  version: ">=0"

env:
- MUSL_TARGET=x86_64-mocaccino-linux-musl
- MUSL_ARCH=x86
- MUSL_CPU=x86-64
- CFLAGS="-I/include -I/usr/include"


package_dir: /pcre2
prelude:
- |
   wget https://iweb.dl.sourceforge.net/project/pcre/${PACKAGE_NAME}/${PACKAGE_VERSION}/${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.gz && \
   tar -xvf ${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.gz && mv ${PACKAGE_NAME}-${PACKAGE_VERSION} ${PACKAGE_NAME} && \
   cd ${PACKAGE_NAME} && mkdir -p /${PACKAGE_NAME} && ./configure --prefix=/usr --enable-unicode         --build=$MUSL_TARGET --host=$MUSL_TARGET           \
            --enable-jit                        \
            --enable-pcre2-16                   \
            --enable-pcre2-32                   \
            --enable-pcre2grep-libz             && make
#            --enable-pcre2grep-libbz2           \
#            --enable-pcre2test-libreadline      \ && make

steps:
- | 
   cd ${PACKAGE_NAME} && make DESTDIR=/${PACKAGE_NAME} install && \
   cp -rfv /${PACKAGE_NAME}/* /
  
