
requires:
- name: musl-toolchain
  category: system
  version: "0.9.9"
- name: make
  category: development
  version: ">=0"
- name: bash
  category: shells
  version: ">=0"

env:
- MUSL_TARGET=x86_64-mocaccino-linux-musl
- MUSL_ARCH=x86
- MUSL_CPU=x86-64
#- GOROOT_BOOTSTRAP=/go_bootstrap
- CGO_ENABLED=0

package_dir: /go
prelude:
- |
   wget https://dl.google.com/go/go1.4-bootstrap-20171003.tar.gz -O go1.4-bootstrap-20171003.tar.gz && \
   mkdir -p $HOME/go && mkdir -p /go/usr/lib && mkdir -p /go/usr/bin && \
   tar -xvf go1.4-bootstrap-20171003.tar.gz -C $HOME/ && mv $HOME/go $HOME/go1.4 && \
   cd $HOME/go1.4/src && bash make.bash && cd ../../../ && mkdir -p /goreal  && \
   wget https://dl.google.com/${PACKAGE_NAME}/${PACKAGE_NAME}${PACKAGE_VERSION}.src.tar.gz -O ${PACKAGE_NAME}${PACKAGE_VERSION}.src.tar.gz && \
   tar -xvf ${PACKAGE_NAME}${PACKAGE_VERSION}.src.tar.gz -C /goreal

steps:
- |
   cd /goreal/go && \
   mkdir -p /${PACKAGE_NAME} && cd src && ls -liah && GOROOT_FINAL=/usr/lib/go bash all.bash && \
   mv /goreal/go /go/usr/lib/go && cd /go/usr/bin/ && ln -s ../lib/go/bin/go go