
requires:
- name: musl-toolchain
  category: system
  version: "0.9.9"
- name: make
  category: development
  version: ">=0"
- name: zlib
  category: libs
  version: ">=0"

env:
- MUSL_TARGET=x86_64-mocaccino-linux-musl
- MUSL_ARCH=x86
- MUSL_CPU=x86-64


package_dir: /git
prelude:
- |
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   wget https://mirrors.edge.kernel.org/pub/software/scm/${PACKAGE_NAME}/${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.gz && \
   tar -xvf ${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.gz && mv ${PACKAGE_NAME}-${PACKAGE_VERSION} ${PACKAGE_NAME} && \
   cd ${PACKAGE_NAME} && mkdir -p /${PACKAGE_NAME} && ./configure --prefix=/usr && make NO_GETTEXT=1 NO_TCLTK=1 DESTDIR=/${PACKAGE_NAME}

steps:
- cd ${PACKAGE_NAME} && make NO_GETTEXT=1 NO_TCLTK=1 DESTDIR=/${PACKAGE_NAME} install && cp -rfv /git/* /
