
requires:
- name: musl-toolchain
  category: system
  version: ">=0"
- name: make
  category: development
  version: ">=0"
- name: zlib
  category: libs
  version: ">=0"
- name: libffi
  category: libs
  version: ">=0"
- name: libressl
  category: libs
  version: ">=0"

env:
- CFLAGS="-Wno-error -I/include -I/usr/include"
- LDFLAGS="-L/usr/lib -L/lib"
- PKG_CONFIG_PATH="/usr/lib/pkgconfig"

package_dir: /ruby

{{- if eq (default $.Values.arch "x86") "x86" }}
steps:
- |
  PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
  curl -L -O  https://cache.ruby-lang.org/pub/{{ .Values.name }}/2.7/{{ .Values.name }}-${PACKAGE_VERSION}.tar.gz && \
  tar -xvf {{ .Values.name }}-${PACKAGE_VERSION}.tar.gz && mv {{ .Values.name }}-${PACKAGE_VERSION} {{ .Values.name }} && \
  cd {{ .Values.name }} && mkdir -p /{{ .Values.name }} && \
  ./configure --prefix=/usr && make -j8 && \
  make DESTDIR=/{{ .Values.name }} install && \
  cp -rfv /{{ .Values.name }}/* / && cd .. && rm -rf ruby
# TODO: replace symlink with update-alternatives
#   cd /${PACKAGE_NAME}/usr/bin && ln -s python3 python && \
{{- end }}
