requires:
- name: musl-arch
  category: system
  version: ">=0"

env:
- TARGET=$MUSL_TARGET

package_dir: "/musl"

# removes libc.so and ld-musl-.*.so.1 from the final package
# to not conflict with system/musl
#TODO: Replace curl with custom version from repo
steps:
- |
  PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
  apk update && \
  apk add git build-base make patch busybox-static curl && \
  curl -L https://github.com/moparisthebest/static-curl/releases/download/v7.80.0/curl-amd64 -o /usr/bin/curl-static && chmod +x /usr/bin/curl-static && \
  mv /usr/bin/curl-static /usr/bin/curl && \
  git clone https://github.com/richfelker/musl-cross-make && \
  cd musl-cross-make && \
  git checkout v${PACKAGE_VERSION} -b build && \
  cp -rfv ../config.mak ./ && \
  rm -rfv patches/linux-headers-4.19.88/* && \
  mkdir -p /musl/ && \
  set -x && \
  patch -Np1 -i ../patches/sysroot.patch && \
  mkdir -p output/bin && \
  make -j 8 && \
  make install && \
  ls -liah output && \
  PATH=$PATH:$PWD/output/bin:$PWD/output/$TARGET/bin make NATIVE=1 -j8 && \
  PATH=$PATH:$PWD/output/bin:$PWD/output/$TARGET/bin make NATIVE=1 install && \
  apk del build-base && \
  cp -rfv /musl/* / && \
  rm -rfv /musl/lib/ld-musl-x86_64.so.1 && \
  rm -rfv /musl/lib/libc.so && \
  rm -rfv /musl/lib/libstdc++* && \
  rm -rfv /musl/lib/libgcc* && \
  cd .. && rm -rf musl-cross-make
