
requires:
- name: musl-toolchain
  category: system
  version: ">=0"
- name: make
  category: development
  version: ">=0"


package_dir: /bash
prelude:
- |
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   wget http://ftp.gnu.org/gnu/${PACKAGE_NAME}/${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.gz && \
   tar -xvf ${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.gz && mv ${PACKAGE_NAME}-${PACKAGE_VERSION} ${PACKAGE_NAME} && \
   cd ${PACKAGE_NAME} && mkdir -p /${PACKAGE_NAME} && ./configure --without-bash-malloc --prefix=/ && make DESTDIR=/${PACKAGE_NAME}

steps:
- cd ${PACKAGE_NAME} && make DESTDIR=/${PACKAGE_NAME} install && cp -rfv /bash/* /
