
requires:
- name: musl-toolchain
  category: system
  version: ">=0"
- name: make
  category: development
  version: ">=0"
- name: zlib
  category: libs
  version: ">=0"

env:
- CFLAGS="-I/usr/include -I/include"

package_dir: /util-linux
prelude:
- |
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   wget https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.35/${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.gz  && \
   tar -xvf ${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.gz && mv ${PACKAGE_NAME}-${PACKAGE_VERSION} ${PACKAGE_NAME} && \
   cd ${PACKAGE_NAME} && mkdir -p /${PACKAGE_NAME} && ./configure --prefix=/usr && make DESTDIR=/${PACKAGE_NAME}

steps:
- |
  cd ${PACKAGE_NAME} && make DESTDIR=/${PACKAGE_NAME} install && \
  cp -rfv /${PACKAGE_NAME}/* /
