requires:
- name: musl-toolchain
  category: system
  version: ">=0"
- name: make
  category: development
  version: ">=0"
- name: perl
  category: lang
  version: ">=0"

package_dir: /busybox
prelude:
- |
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   curl -L -O  https://busybox.net/downloads/${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.bz2 && \
   tar -xvjf ${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.bz2 && mv ${PACKAGE_NAME}-${PACKAGE_VERSION} ${PACKAGE_NAME} && \
   cd ${PACKAGE_NAME} && mkdir -p /${PACKAGE_NAME} && make defconfig && make CONFIG_PREFIX=/${PACKAGE_NAME}

steps:
- cd ${PACKAGE_NAME} && make CONFIG_PREFIX=/${PACKAGE_NAME} install
- mkdir -p /${PACKAGE_NAME}/usr/share/udhcpc/ && cp -rfv udhcpc.conf /${PACKAGE_NAME}/usr/share/udhcpc/default.script
- chmod +x /${PACKAGE_NAME}/usr/share/udhcpc/default.script
- mv /${PACKAGE_NAME}/sbin/init busybox-init
- mv /${PACKAGE_NAME}/linuxrc busybox-linuxrc
- mv /${PACKAGE_NAME}/sbin/halt busybox-halt
- mv /${PACKAGE_NAME}/sbin/poweroff busybox-poweroff
- mv /${PACKAGE_NAME}/sbin/reboot busybox-reboot

excludes:
# Shipped by utils/xz
- /usr/bin/xz
- /usr/bin/unxz
# Shipped by kmod
- /sbin/depmod
- /sbin/lsmod
- /sbin/modprobe