
requires:
- name: musl-toolchain
  category: system
  version: ">=0"
- name: make
  category: development
  version: ">=0"
- name: perl
  category: lang
  version: ">=0"

package_dir: /texinfo
prelude:
- |
   curl -L -O  http://ftp.gnu.org/gnu/${PACKAGE_NAME}/${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.gz && \
   tar -xvf ${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.gz && mv ${PACKAGE_NAME}-${PACKAGE_VERSION} ${PACKAGE_NAME} && \
   cd ${PACKAGE_NAME} && mkdir -p /${PACKAGE_NAME} && ./configure PERL=/usr/bin/perl --prefix=/usr && make

steps:
- | 
   cd ${PACKAGE_NAME} && make DESTDIR=/texinfo install && \
   cp -rfv /${PACKAGE_NAME}/* /
  
