name: Build

on: [push, pull_request]

jobs:

  generate-matrix:
    
    name: Generate matrix for build
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - name: Install deps
        run: |
          curl https://get.mocaccino.org/luet/get_luet_root.sh | sudo sh
          sudo luet install utils/jq
      - name: Set matrix for build
        id: set-matrix
        run: |
          JSON="{\"include\":"
          JSONline="$(luet tree pkglist --tree packages -o json | jq -rc '.packages')"
          JSON="$JSON$JSONline"
          JSON="$JSON}"
          # Set output
          echo "::set-output name=matrix::$( echo "$JSON" )"
  build:
    needs: generate-matrix
    strategy:
      matrix: ${{fromJson(needs.generate-matrix.outputs.matrix)}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Release space from worker
      run: |
        sudo rm -rf /usr/local/lib/android # will release about 10 GB if you don't need Android
        sudo rm -rf /usr/share/dotnet # will release about 20GB if you don't need .NET
    - run: |
        git fetch --prune --unshallow
    - name: Build 🔧
      uses: mudler/luet-github-action@master
      if: ${{ github.event_name != 'push' }}
      with:
        # tree: packages
        build: true
        onlyMissing: true
        FINAL_REPO: quay.io/mocaccino/micro
        values: arches/amd64/values.yaml
        pushCache: false
        CURRENT_PACKAGE:  ${{ matrix.category }}/${{ matrix.name }}@${{ matrix.version }}
    - name: Build 🔧
      uses: mudler/luet-github-action@master
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      with:
        # tree: packages
        build: true
        FINAL_REPO: quay.io/mocaccino/micro
        onlyMissing: true
        values: arches/amd64/values.yaml
        pushCache: true
        DOCKER_USERNAME: ${{ secrets.QUAY_ROBOT_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.QUAY_ROBOT_PASSWORD }}
        DOCKER_ENDPOINT: quay.io
        CURRENT_PACKAGE:  ${{ matrix.category }}/${{ matrix.name }}@${{ matrix.version }}
        # Repository used to pull images from. needed if you list any repo in .luet.yaml
      #PULL_REPOSITORY: quay.io/mocaccinocache/desktop
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.category }}-${{ matrix.name }}-${{ matrix.version }}.zip
        path: |
          build/
  create-repo:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --prune --unshallow

    - name: Download all workflow run artifacts
      uses: actions/download-artifact@v2
    - name: Merge artifacts 🔧
      run: |
        mkdir build || true
        for i in $(ls | grep zip); do
          cp -rfv $i/* build
        done
        ls -liah
        ls -liah build
    - name: Download meta
      uses: mudler/luet-github-action@master
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      with:
        # tree: packages
        downloadMeta: true
        downloadAllMeta: true
        FINAL_REPO: quay.io/mocaccino/micro
        REPOSITORY_TYPE: docker
    - name: Create repo 🔧
      uses: mudler/luet-github-action@master
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
      with:
        # tree: packages
        createRepo: true
        pushCache: true
        DOCKER_USERNAME: ${{ secrets.QUAY_ROBOT_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.QUAY_ROBOT_PASSWORD }}
        DOCKER_ENDPOINT: quay.io
        FINAL_REPO: quay.io/mocaccino/micro
        REPOSITORY_TYPE: docker
