
requires:
- name: musl-toolchain
  category: system
  version: ">=0"
- name: make
  category: development
  version: ">=0"
- name: python
  category: lang
  version: ">=0"

env:
- CFLAGS="-I/usr/include -I/include"

package_dir: /ca-certificates
prelude:
- |
   PACKAGE_VERSION=${PACKAGE_VERSION%\+*} && \
   wget https://gitlab.alpinelinux.org/alpine/${PACKAGE_NAME}/-/archive/${PACKAGE_VERSION}/${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.bz2 && \
   tar -xvf ${PACKAGE_NAME}-${PACKAGE_VERSION}.tar.bz2 && mv ${PACKAGE_NAME}-${PACKAGE_VERSION} ${PACKAGE_NAME} && \
   cd ${PACKAGE_NAME} && mkdir -p /${PACKAGE_NAME} && CC=gcc make && \
   rm AddTrust_External_Root.crt

steps:
- | 
  cd ${PACKAGE_NAME} && \
  make DESTDIR=/${PACKAGE_NAME} install && \ 
  sh ../gen_ca.sh && \ 
  cp -rfv /${PACKAGE_NAME}/* /
